reporting:
    tables:
        facts:
            - factorderline:
                col_names: [order_line_id, product_id, order_date, ship_date, customer_id, campaign_id, order_status_id, quantity, total_discount, total_price, total_cost]
                table_group: order
            - factorderline_product:
                col_names: [product_id, quantity, total_discount, total_price, total_cost]
                table_group: order
            - factinventoryevent:
                col_names: [product_id, quantity, event_date, unit_cost]
                table_group: inven
        dimensions:
            - dimproduct:
                col_names: [product_id, name, curr_price]
            - dimcustomer:
                col_names: [customer_id, name]
    measures:
        - summed_total_cost:
            required_cols: [total_cost]
            cols: 
                - summed_total_cost: 
                    sql: "total_cost"
                    filter_type: DECIMAL
                    display_type: MONEY
                    aggregation_type: SUM
        - total_quantity:
            required_cols: ["quantity"]
            cols:
                - total_quantity: 
                    sql: "quantity"
                    filter_type: INT
                    display_type: INT
                    aggregation_type: SUM
        - total_unit_cost:
            required_cols: ["quantity", "unit_cost"]
            cols:
                - total_unit_cost: 
                    sql: "quantity * unit_cost"
                    filter_type: INT
                    display_type: INT
                    aggregation_type: SUM
        - avg_total_cost:
            required_cols: [total_cost, quantity]
            cols: 
                - avg_total_cost: 
                    sql: ["total_cost", "quantity"]
                    filter_type: DECIMAL
                    display_type: MONEY
                    aggregation_type: DIV
    dimensions:
        - product:
            base_table: dimproduct
            required_cols: [product_id]
            cols:
                - product_id: 
                    sql: "fact.product_id"
                    filter_type: INT
                    display_type: INT
                    aggregation_type: GROUPBY
                - name: 
                    sql: "prod.name"
                    filter_type: STRING
                    display_type: STRING
                    aggregation_type: AFTERGROUPBY
                - curr_price: 
                    sql: "prod.curr_price"
                    filter_type: DECIMAL
                    aggregation_type: AFTERGROUPBY
                    display_type: MONEY
            join_alias: "prod"
        - order_date:
            required_cols: [order_date]
            cols:
                - order_date: 
                    sql: "fact.order_date"
                    filter_type: TIMESTAMP
                    display_type: TIMESTAMP
                    aggregation_type: GROUPBY
        - customer:
            required_cols: [customer_id]
            base_table: dimcustomer
            cols:
                - customer_id: 
                    sql: "fact.customer_id"
                    filter_type: INT
                    display_type: INT
                    aggregation_type: GROUPBY
                - name: 
                    sql: "cust.name"
                    filter_type: STRING
                    display_type: STRING
                    aggregation_type: AFTERGROUPBY
            join_alias: "cust"
    reports:
        - "Yearly totals by Customer":
            cols: ["customer.name", "customer_id", "avg_total_cost", "summed_total_cost"]
            filters:
            - order_date:
                filter_operator: BETWEEN
                min: "2016-01-01"
                max: "2016-12-31"
        - "Product totals":
            cols: ["product.name", "summed_total_cost", "total_quantity"]
        - "Product totals with funky filter":
            cols: ["product.name", "summed_total_cost", "total_quantity"]
            filters:
                - customer.name:
                    filter_operator: SUBSTRING
                    value: "foobar"
        - "Products by Customer":
            cols: ["customer.name", "product.name", "avg_total_cost", "summed_total_cost", "total_quantity"]
        - "Products by Customer Filtered":
            cols: ["customer.name", "product.name", "avg_total_cost", "summed_total_cost", "total_quantity"]
            filters:
                - customer.name:
                    filter_operator: SUBSTRING
                    value: "foobar"
                - product_id:
                    filter_operator: EQUALS
                    value: "12345"
                - product_id:
                    filter_operator: EQUALS
                    value: "12345666"
        - "Product ids":
            cols: [product_id, summed_total_cost]
            filters:
                - product_id:
                    filter_operator: GREATER
                    value: "3"
        - "Product ids null":
            cols: [product_id, summed_total_cost]
            filters:
                - product_id:
                    filter_operator: EQUALS
                    value: null
        - "All Products":
            cols: [product.name, product_id]
        - "All Products on hand":
            cols: [product.name, inven.total_quantity]
        - "All Products sold":
            cols: [product.name, order.total_quantity]
        - "All Products sold price and inventory total cost":
            cols: [product.name, order.summed_total_cost, inven.total_unit_cost]
        - "All Products sold price and inventory total cost with prod_id":
            cols: [product.name, order.summed_total_cost, inven.total_unit_cost, product_id]
        - "All Products num products sold and on hand":
            cols: [product.name, order.total_quantity, inven.total_quantity]
        - "All Products num products sold and on hand by customer":
            cols: [product.name, order.total_quantity, inven.total_quantity, customer.name]
